### ISSUE TITLE
Updater crash loading plugin - 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by JeNeSuisPasDave** [Monnoroch/ColorHighlighter#194]
Using ST3 build 3069, I see this in the console log after launch:

```
reloading plugin Color Highlighter.ColorHighlighter
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 127, in reload_plugin
    el.on_activated(v)
  File "ColorHighlighter in /Users/datihein/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 1428, in on_activated
  File "ColorHighlighter in /Users/datihein/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 938, in on_activated
  File "ColorHighlighter in /Users/datihein/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 886, in init
TypeError: 'NoneType' object is not iterable
reloading Packages/Color Highlighter/ColorHighlighter.sublime-settings
reloading plugin Color Highlighter.colors
```

**Comment by NotSqrt** [comment]
:+1: 

Same error with ST 3075.

**Comment by NotSqrt** [comment]
Fixed it by copying the ``color_formats`` setting from the defaults to the user settings.

**Comment by Monnoroch** [comment]
Should be fixed in V7.
