### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by byaka** [Monnoroch/ColorHighlighter#217]
```python
Traceback (most recent call last):
  File "./sublime_plugin.py", line 200, in on_selection_modified
  File "./sublime_plugin.py", line 154, in run_timed_function
  File "./sublime_plugin.py", line 199, in <lambda>
  File "./ColorHighlighter.py", line 1425, in on_selection_modified
  File "./ColorHighlighter.py", line 997, in on_selection_modified
  File "./ColorHighlighter.py", line 565, in update
  File ".\encodings\utf_8.py", line 16, in decode
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 6493: ordinal not in range(128)
```

file, where i have this error https://drive.google.com/file/d/0B69BLzwAiOiTUVNQOTZFc0hnTkU/view?usp=sharing

**Comment by Monnoroch** [comment]
Should be fixed in brand new V7.

**Comment by byaka** [comment]
Thx for new version. I'm install it, but...
```python
Traceback (most recent call last):
  File "./sublime_plugin.py", line 175, in on_load
  File "./sublime_plugin.py", line 154, in run_timed_function
  File "./sublime_plugin.py", line 174, in <lambda>
  File "./ColorHighlighter.py", line 1507, in on_load
  File "./ColorHighlighter.py", line 1110, in on_load
  File "./ColorHighlighter.py", line 854, in on_activated
  File "./ColorHighlighter.py", line 1051, in add_colors
  File "./ColorHighlighter.py", line 173, in flush
  File ".\encodings\utf_8.py", line 16, in decode
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 4783: ordinal not in range(128)
```
and all colors are 'black'
![image](https://cloud.githubusercontent.com/assets/1580811/9409239/a437bb72-4821-11e5-96ca-cbe51cbdd383.png)

**Comment by Monnoroch** [comment]
What ST version and OS?

**Comment by byaka** [comment]
ST 2.0.2 build 2221
Ubuntu 14.04

**Comment by Monnoroch** [comment]
Ok, thanks, I'll check. But could you also tell me, what color scheme do you use?
It seems to be non-utf-8 encoded.

**Comment by byaka** [comment]
I'm use standart 'Dawn' theme

**Comment by byaka** [comment]
when i'm try to change theme to another, i see
```python
error: Error loading colour scheme Packages/User/Color Highlighter/themes/Twilight.tmTheme: Error parsing plist xml: Failed to open file In file "Packages/User/Color Highlighter/themes/Twilight.tmTheme"
theme loaded
```
When back to Dawn, no errors.

**Comment by Monnoroch** [comment]
Ok, could you please replace the ColorHighlighter.py file to a version in a branch v7 of this repo, and let me know, if it did fix the problem?

**Comment by byaka** [comment]
![image](https://cloud.githubusercontent.com/assets/1580811/9409704/00e2c9d6-4825-11e5-95a2-635b7204a668.png)

**Comment by Monnoroch** [comment]
Oh. Sorry, it seems that I use ST3 specific api. One moment.

**Comment by Monnoroch** [comment]
Could you please try again?

**Comment by byaka** [comment]
It's work! Big thx, you my hero :smile:

**Comment by Monnoroch** [comment]
Ok, I'll update the master in a minute.
