### ISSUE TITLE
Does not work at all. Getting UnicodeEncodeError.

### ISSUE THREAD

**Issue by MiChAeLoKGB** [Monnoroch/ColorHighlighter#228]
Here is error I am getting. I get this error anytime I click anywhere in my file... That character its screaming about is small Pi => π
I dont have that anywhere in my file tho. Da F?

    Traceback (most recent call last):
      File ".\sublime_plugin.py", line 200, in on_selection_modified
      File ".\sublime_plugin.py", line 154, in run_timed_function
      File ".\sublime_plugin.py", line 199, in <lambda>
      File ".\ColorHighlighter.py", line 1425, in on_selection_modified
      File ".\ColorHighlighter.py", line 997, in on_selection_modified
      File ".\ColorHighlighter.py", line 565, in update
      File ".\encodings\utf_8.py", line 16, in decode
    UnicodeEncodeError: 'ascii' codec can't encode character u'\u03c0' in position 260: ordinal not in range(128)

Using SublimeText 2 on WIN 7 Ultimate 64bit.

Same error: https://github.com/Monnoroch/ColorHighlighter/issues/217 (did nto see that one, othervise I would not create duplicite post).

Ps.: I tried it in ST 3 and it works there... So this error is only ST 2 related.

**Comment by Monnoroch** [comment]
Sould be fixed in brand new V7.
