### ISSUE TITLE
Recent update: Choose color doesnt work for hex6 format

### ISSUE THREAD

**Issue by mahadi** [Monnoroch/ColorHighlighter#239]
I have a python color list

````python
colors = [0x00FFFF, 0x000000, 0x0000FF, 0xFF00FF, 0x808080, 0x008000,
               0x00FF00, 0x800000, 0x000080, 0x808000, 0x800080, 0xFF0000,
               0xC0C0C0, 0x008080, 0xFFFFFF, 0xFFFF00]
```

When i right click on a highlighted color and select "choose color" then the selected color wont be replaced in code. For hex8 it`s working.

Error in console:

```bash
ChReplaceColor: {'words': "((1876, 1884), 'hex6', '#FF0000FF')"}
Traceback (most recent call last):
  File "D:\Programme\\sublimetext3\sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
  File "ColorHighlighter in D:\Programme\sublimetext3\Data\Installed Packages\Color Highlighter.sublime-package", line 1587, in run
  File "ColorHighlighter in D:\Programme\sublimetext3\Data\Installed Packages\Color Highlighter.sublime-package", line 663, in convert_back_color
  File "ColorHighlighter in D:\Programme\sublimetext3\Data\Installed Packages\Color Highlighter.sublime-package", line 549, in get_col_color
IndexError: no such group
```

**Comment by Monnoroch** [comment]
Fixed!
