### ISSUE TITLE
Highlighting Does Not Work; Context Menu Grayed Out

### ISSUE THREAD

**Issue by pmarshwx** [Monnoroch/ColorHighlighter#242]
I installed this plugin from the Package Manager today and highlighting doesn't work. Additionally, the Context Menu is grayed out. I checked the log and the plugin is producing the following error:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 304, in on_activated
    callback.on_activated(v)
  File "ColorHighlighter in /Users/pmarshwx/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 1548, in on_activated
  File "ColorHighlighter in /Users/pmarshwx/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 1157, in on_activated
  File "ColorHighlighter in /Users/pmarshwx/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 851, in on_activated
  File "ColorHighlighter in /Users/pmarshwx/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 827, in on_selection_modified
  File "ColorHighlighter in /Users/pmarshwx/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 1279, in get_vars
AttributeError: 'NoneType' object has no attribute 'get'
```

I'm currently using ST3, Build 3083.

EDIT: I should add that I don't know enough about this plugin (yet) to go digging around.

**Comment by Monnoroch** [comment]
Fixed @https://github.com/Monnoroch/ColorHighlighter/commit/dbde2700be2a2438bfecd5ea461b4dba2024c9d6

**Comment by pmarshwx** [comment]
Since the Package Manager hasn't been updated yet, I installed from the repository.

Initially, I had the following issues:

```
startup, version: 3083 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/pmarshwx/Library/Application Support/Sublime Text 3/Packages
state path: /Users/pmarshwx/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/pmarshwx/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage", "Anaconda"]
pre session restore time: 0.229552
first paint time: 0.294666
startup time: 0.308396
...<snip>...
reloading plugin ColorHighlighter.ColorHighlighter
Traceback (most recent call last):
  File "/Users/pmarshwx/Library/Application Support/Sublime Text 3/Packages/ColorHighlighter/ColorHighlighter.py", line 16, in <module>
    import colors
ImportError: No module named 'colors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/pmarshwx/Library/Application Support/Sublime Text 3/Packages/ColorHighlighter/ColorHighlighter.py", line 18, in <module>
    colors = __import__(plugin_name, fromlist=["colors"]).colors
ImportError: No module named 'Color Highlighter'
...<snip>...
```

This appears to be due to the space between "Color" and "Highlighter" in the plugin_name variable in ColorHighlighter.py

When removing this space and restarting, the plugin loads, but on use the following error occurs:

```
reloading plugin ColorHighlighter.ColorHighlighter
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 127, in reload_plugin
    el.on_activated(v)
  File "/Users/pmarshwx/Library/Application Support/Sublime Text 3/Packages/ColorHighlighter/ColorHighlighter.py", line 1592, in on_activated
    color_highlighter.on_activated(view)
  File "/Users/pmarshwx/Library/Application Support/Sublime Text 3/Packages/ColorHighlighter/ColorHighlighter.py", line 1197, in on_activated
    self.views[view.id()].on_activated()
  File "/Users/pmarshwx/Library/Application Support/Sublime Text 3/Packages/ColorHighlighter/ColorHighlighter.py", line 890, in on_activated
    self.on_selection_modified()
  File "/Users/pmarshwx/Library/Application Support/Sublime Text 3/Packages/ColorHighlighter/ColorHighlighter.py", line 865, in on_selection_modified
    vs = self.ch.get_vars(self.view)
  File "/Users/pmarshwx/Library/Application Support/Sublime Text 3/Packages/ColorHighlighter/ColorHighlighter.py", line 1338, in get_vars
    if color_vars_file is not None:
UnboundLocalError: local variable 'color_vars_file' referenced before assignment
```

**Comment by Monnoroch** [comment]
plugin_name must contain that space if you install from the Package Control.
Otherwise, it's just the plugin directory name.
Since you've renamed the dir, you had to rename the variable.

**Comment by pmarshwx** [comment]
Thanks for the quick replies. I was able to install from Package Control this afternoon and it works.

Thanks again.
