### ISSUE TITLE
Newest version broken

### ISSUE THREAD

**Issue by ob7** [Monnoroch/ColorHighlighter#247]
File "ColorHighlighter in /home/user/.config/sublime-text-3/Installed Packages/Color Highlighter.sublime-package", line 1182, in on_selection_modified
  File "ColorHighlighter in /home/user/.config/sublime-text-3/Installed Packages/Color Highlighter.sublime-package", line 866, in on_selection_modified
  File "ColorHighlighter in /home/user/.config/sublime-text-3/Installed Packages/Color Highlighter.sublime-package", line 1333, in get_vars
  File "ColorHighlighter in /home/user/.config/sublime-text-3/Installed Packages/Color Highlighter.sublime-package", line 1313, in get_file_vars

**Comment by Monnoroch** [comment]
Could you provide the full log, as well as your OS and ST version?

**Comment by ob7** [comment]
How do I provide the log?  Where so I find it.  Its on a fresh install of Arch Linux and Sublime Text 3.

**Comment by Monnoroch** [comment]
Well, you did copy it from the console, you just didn't copy enough.

**Comment by wldcordeiro** [comment]
@Monnoroch I'm not sure exactly what his issue is since it's lacking in details but it appears that the newest update will now override syntax specific color schemes with the default user one and that could be related to @ob7's issue.

**Comment by antenando** [comment]
Hey @Monnoroch , sorry to jump in the conversation, but my ST3 console keeps being flooded by the plugin. It highlights my files just right, but floods the console with this very same error

```
KeyError: '/Users/lbueno/work/www/front-end/oi-bradesco/src/_assets/scss/mixins.scss'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 288, in on_selection_modified
    callback.on_selection_modified(v)
  File "ColorHighlighter in /Users/lbueno/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 1596, in on_selection_modified
  File "ColorHighlighter in /Users/lbueno/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 1196, in on_selection_modified
  File "ColorHighlighter in /Users/lbueno/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 877, in on_selection_modified
  File "ColorHighlighter in /Users/lbueno/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 1347, in get_vars
  File "ColorHighlighter in /Users/lbueno/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 1327, in get_file_vars
  File "ColorHighlighter in /Users/lbueno/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 1324, in _get_vars
  File "ColorHighlighter in /Users/lbueno/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 1327, in get_file_vars
KeyError: '/Users/lbueno/work/www/front-end/oi-bradesco/src/_assets/scss/mixins.scss'
```
and it's always the same lines, the same errors:

```
  line 1608, in on_activated
  line 1212, in on_activated
  line 902, in on_activated
  line 877, in on_selection_modified
  line 1347, in get_vars
  line 1327, in get_file_vars
  line 1324, in _get_vars
  line 1327, in get_file_vars
  line 1324, in _get_vars
  line 1327, in get_file_vars
```

Thanks in advance

**Comment by notami** [comment]
I'm getting the same errors as antenando but highlight is NOT working. Also menu under "Tools>Color Highlighter" is intermittent, sometimes incomplete, sometimes greyed out.

**Comment by Monnoroch** [comment]
@antenando could you provide a minimal example (current file plus the file that's in the console) to reproduce the problem?

**Comment by Monnoroch** [comment]
@antenando wait, does this file in the error message even exist?

**Comment by antenando** [comment]
@Monnoroch You solved it and now it works flawlessly, thanks again!

But answering your question, yes sure the file exists.

**Comment by Monnoroch** [comment]
Then could you please provide a minimal example? Because I didn't fix the reason, only a symptom.

**Comment by antenando** [comment]
It was a mixins scss file, which had
```
#wrapper {
     @include bs-xxs {
         border-top: 5px solid green;
     }
     @include bs-xs {
         border-top: 5px solid green;
     }
     @include bs-sm {
         border-top: 5px solid yellow;
     }
     @include bs-md {
         border-top: 5px solid blue;
     }
     @include bs-lg {
         border-top: 5px solid gray;
     }
}
```
for debugging purposes
