### ISSUE TITLE
"Choose color" failure with rgb and #

### ISSUE THREAD

**Issue by samit4me** [Monnoroch/ColorHighlighter#255]
Firstly I just wanted to say a hug thanks for creating ColorHighlighter it is awesome.

The color change is working for "@named" and "sharp8", but unfortunately I am having trouble with anything below sharp8 (e.g. sharp6, rgb etc). I am not a python developer or have any experience developing for sublime, but keen to help if there is anything I can do. 

#### My Environment
* OS X 10.10.5
* ST3
* ImageMagick 6.9.0
* ColorHighlighter 2015.08.25.11.08.19

#### Steps to reproduce
* Place cursor on value **rgb(255, 0 0)**
* ctrl+shft+c
* Select green and click ok
* Below is the error in sublime console

 ```
ChReplaceColor: {'words': "((17, 29), 'rgb', '#00FF00FF')"}
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
  File "ColorHighlighter in /Users/sam/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 1678, in run
  File "ColorHighlighter in /Users/sam/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 704, in convert_back_color
  File "ColorHighlighter in /Users/sam/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 588, in get_col_color
IndexError: no such group
```

Like I said earlier I don't know python but I took a look at ColorHighlighter.py and it appears to be looking for a "types" key in ColorHighlighter.sublime-settings which doesn't exist and I can't seem to edit that file, any help appreciated.

```python
 def _col_to_chans_match(self, col, fmt, match): # -> chans
        types_orig = self.conf[fmt]["types"]

        # easy way: choose the first channel type
        # TODO: better way!
        chs = ["R", "G", "B", "A"]
```

**Comment by Monnoroch** [comment]
Please, provide the test sample.

**Comment by samit4me** [comment]
1) Create file **test.css** with the following and saved to disk:
```css
.test {
  color: rgb(255,0,0);
}
```
2) Place cursor on value **rgb(255, 0 0)**
3) ctrl+shft+c
4) Select green and click ok
5) Below is the error in sublime console

 ```
ChReplaceColor: {'words': "((17, 29), 'rgb', '#00FF00FF')"}
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
  File "ColorHighlighter in /Users/sam/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 1678, in run
  File "ColorHighlighter in /Users/sam/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 704, in convert_back_color
  File "ColorHighlighter in /Users/sam/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 588, in get_col_color
IndexError: no such group
```

Got this same problem on multiple machines, hope this is what you were asking for?

**Comment by samit4me** [comment]
Tested and now working, thank you so much.
