### ISSUE TITLE
Problem running plugin: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by garrypolley** [Monnoroch/ColorHighlighter#273]
I've installed this plugin via package control in sublime text 3. Below is the error I get in the sublime text console when running the plugin. 

```py
Traceback (most recent call last):
  File "ColorHighlighter in /Users/garrypolley/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 305, in <lambda>
  File "ColorHighlighter in /Users/garrypolley/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 328, in on_change
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "ColorHighlighter in /Users/garrypolley/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 2034, in <lambda>
  File "ColorHighlighter in /Users/garrypolley/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 2032, in run_when_cs_loaded
  File "ColorHighlighter in /Users/garrypolley/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 2028, in ch_start
  File "ColorHighlighter in /Users/garrypolley/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 1376, in __init__
  File "ColorHighlighter in /Users/garrypolley/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 1449, in _add_view
  File "ColorHighlighter in /Users/garrypolley/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 1080, in enable
  File "ColorHighlighter in /Users/garrypolley/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 1085, in redraw
  File "ColorHighlighter in /Users/garrypolley/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 985, in on_activated
  File "ColorHighlighter in /Users/garrypolley/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 1018, in _on_activated_impl
  File "ColorHighlighter in /Users/garrypolley/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 998, in _on_selection_modified_impl
  File "ColorHighlighter in /Users/garrypolley/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 1578, in get_vars
  File "ColorHighlighter in /Users/garrypolley/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 1214, in get_vars
  File "ColorHighlighter in /Users/garrypolley/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 1324, in get_file_vars
........
  File "ColorHighlighter in /Users/garrypolley/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 1320, in _get_vars
RuntimeError: maximum recursion depth exceeded
```

I'm not sure what is going wrong, but I think the plugin used to work in the past and now it's not really working at all. I removed it and reinstalled and still get this issue.

**Comment by Monnoroch** [comment]
Could you provide a minimal example of the files to reproduce the bug?

**Comment by garrypolley** [comment]
This repository: https://github.com/garrypolley/style-site

Whenever I look at the LESS files here https://github.com/garrypolley/style-site/tree/master/assets/less that's when I get the error. Thanks for checking it out.
