### ISSUE TITLE
OSError: resource not found in load_binary_resource

### ISSUE THREAD

**Issue by evandrocoan** [Monnoroch/ColorHighlighter#380]
I got this when starting Sublime Text:
```
Traceback (most recent call last):
  File "D:\3144\sublime_plugin.py", line 210, in on_api_ready
    m.plugin_loaded()
  File "main in C:\Sublime Text 3\Installed Packages\ColorHighlighter.sublime-package", line 628, in plugin_loaded
  File "main in C:\Sublime Text 3\Installed Packages\ColorHighlighter.sublime-package", line 617, in _init_color_picker
  File "load_resource in C:\Sublime Text 3\Installed Packages\ColorHighlighter.sublime-package", line 60, in get_binary_resource_size
  File "D:\3144\sublime.py", line 199, in load_binary_resource
    raise IOError("resource not found")
OSError: resource not found
```

The lines are:
```python
File: Data/Packages/ColorHighlighter/load_resource.py
51: def get_binary_resource_size(file_path):
52:     """
53:     Polyfill for ST3 sublime.load_binary_resource function.
54: 
55:     Arguments:
56:     - file_path - a resource path.
57:     Returns a byte string with the resource's content.
58:     """
59:     if st_helper.is_st3():
60:         return len(sublime.load_binary_resource(file_path))
61: 
62:     file_path = os.path.join(os.path.dirname(path.packages_path(path.ABSOLUTE)), file_path)
63:     return os.path.getsize(file_path)
```
```python
File: Data/Packages/ColorHighlighter/main.py
613:     def _init_color_picker():
614:         color_picker_file = path.color_picker_file(path.ABSOLUTE)
615:         color_picker_resource = path.color_picker_binary(path.RELATIVE)
616:         if (os.path.exists(color_picker_file) and
617:                 os.path.getsize(color_picker_file) == get_binary_resource_size(color_picker_resource)):
618:             return
```

**Comment by Monnoroch** [comment]
Your installation is incorrect. The name of the package is not `ColorHighlighter.sublime-package`, it's `Color Highlighter.sublime-package`. Alternatively `Packages/ColorHighlighter/` directory is supported for developers, but not `ColorHighlighter.sublime-package`

**Comment by Monnoroch** [comment]
Since you installing the plugin in a custom way, I assume you have experience developing packages. If this is the case, you can send a PR for supporting these other package names, if you think it's important. But the code has to be simple, otherwise it's not worth it.
