### ISSUE TITLE
ColorHighter 8.0 stop working on macos 10.12.6 SublimeText3 Build 3143

### ISSUE THREAD

**Issue by iPPLE** [Monnoroch/ColorHighlighter#383]
There is not color highlight on the color code.

**Comment by CinKon** [comment]
#378

**Comment by Monnoroch** [comment]
You need to provide:
- OS.
- ST version.
- ST logs.
- a screenshot

**Comment by Nobiuss** [comment]
i have the same problem.

osx 10.13

sublime 3.0 build 3143

**Comment by TheHanna** [comment]
@iPPLE @Nobiuss 

I had a similar issue on macOS 10.12.6, but managed to resolve it by playing around with the highlighting settings in `Tools > Color Highlighter`. I think it may be due to the fact that 8.0 has a completely different settings structure and wipes any previous user settings. Hopefully this helps you too!

**Comment by 123cnm** [comment]
it works for a short time yesterday,but it doesn't work today ,I don't know why! I have tried many times!

**Comment by Monnoroch** [comment]
A bug report has to contain:
- an OS version.
- a ST version.
- A screenshot.
- The plugin settings.
- The color scheme name.
- ST logs.

**Comment by firebolt55439** [comment]
@Monnoroch Does not work on MBP 2017 on version 10.13 on Sublime Text 3.0 Build 3143. Theme used is Boxy. Got this log error:
```
plugins loaded
Traceback: error.

Output:


Error:
/bin/sh: convert: command not found

Highlighting colors with gutter icons is not supported with current ImageMagick setup. Try configuring the "icon_factory setting"
```

Screenshot attached.
<img width="1069" alt="screen shot 2017-10-07 at 12 56 27 pm" src="https://user-images.githubusercontent.com/1293223/31311338-40a26154-ab5f-11e7-9ba3-60c7dab1c68e.png">

**Comment by Monnoroch** [comment]
@iPPLE named colors are not supported yet #381. Error is due to ImageMagick not being installed and is not relevant in this case.

**Comment by firebolt55439** [comment]
@Monnoroch I figured it out. Looks like the default ColorHighlighter settings are different than what I'm used to. Needed to configure highlighting, etc. and disable gutter icons entirely.

**Comment by Monnoroch** [comment]
@firebolt55439 it gets disabled automatically after the error you saw, but yeah. New features -- new configs.

**Comment by iPPLE** [comment]
Color Highlighter v8.0 is not working : 
. MacOS Hight Sierra 10.13.1
. Sublime Text 3 Stable version Build 3143
. Color Scheme "color_scheme": "Packages/Materialize/schemes/Material Glacier.tmTheme",
  Note : not working with all color schemes
. Log : 
  
> Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 210, in on_api_ready
    m.plugin_loaded()
  File "main in /Users/praseth/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 603, in plugin_loaded
  File "settings in /Users/praseth/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 32, in __init__
  File "settings in /Users/praseth/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 97, in __init__
  File "settings in /Users/praseth/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 116, in __init__
  File "settings in /Users/praseth/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 132, in __init__
  File "settings in /Users/praseth/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 191, in __init__
AssertionError
environment variables loaded using: /bin/bash -l
Package Control: Skipping automatic upgrade, last run at 2017-11-29 10:15:56, next run at 2017-11-29 11:15:56 or after

. Screenshot : 
![image](https://user-images.githubusercontent.com/8819027/33357567-62d6deca-d4f5-11e7-9275-068948286d2a.png)

**Comment by ezeeyahoo** [comment]
Even in latest 10.13, I am facing this issue. Any other alternate anyone of you used?
