### ISSUE TITLE
xml.etree.ElementTree.ParseError: XML or text declaration not at start of entity: line 6, column 0

### ISSUE THREAD

**Issue by LeBlaaanc** [Monnoroch/ColorHighlighter#393]
I'm having issues getting Color Highlighter working after upgrading to 8.0.

**OS Version:** OSX 10.12.6
**ST Version:** Dev 3147
![image](https://user-images.githubusercontent.com/2807897/31347230-42756624-ace1-11e7-9784-106ab781b46e.png)
**Color Highlighter Settings:**
```
{
	"autoreload":
	{
		"when_color_scheme_change": true,
		"when_settings_change": true
	},
	"debug": false,
	"default_keybindings": true,
	"experimental":
	{
		"asynchronosly_update_color_scheme": false
	},
	"file_extensions":
	[
		".css",
		".less",
		".scss",
		".sass",
		".styl"
	],
	"icon_factory":
	{
		"convert_command": "convert",
		"convert_timeout": 5
	},
	"regex_compiler":
	{
		"channels":
		{
			"dec": "\\d{1,3}",
			"float": "(?:[0|1])|(?:[1][\\.]?[0]*)|(?:[0]?[\\.]\\d*)",
			"hex": "[0-9a-fA-F]",
			"perc": "(?:\\d{1,3}[%])|(?:0)"
		},
		"formats":
		{
			"hsl":
			{
				"description": "hsl(hue 0..360, s%, v%) color format",
				"regex": "hsl[(][ ]*(?P<H>dec)[ ]*[,][ ]*(?P<S>perc)[ ]*[,][ ]*(?P<L>perc)[ ]*[)]",
				"white": "hsl(0, 0%, 100%)"
			},
			"hsla":
			{
				"description": "hsla(hue 0..360, s%, v%, alpha 0.0 .. 1.0) color format",
				"regex": "hsla[(][ ]*(?P<H>dec)[ ]*[,][ ]*(?P<S>perc)[ ]*[,][ ]*(?P<L>perc)[ ]*[,][ ]*(?P<A>float)[ ]*[)]",
				"white": "hsla(0, 0%, 100%, 1.)"
			},
			"hsv":
			{
				"description": "hsv(hue 0..360, s%, v%) color format",
				"regex": "hsv[(][ ]*(?P<H>dec)[ ]*[,][ ]*(?P<S>perc)[ ]*[,][ ]*(?P<V>perc)[ ]*[)]",
				"white": "hsv(0, 0%, 100%)"
			},
			"hsva":
			{
				"description": "hsva(hue 0..360, s%, v%, alpha 0.0 .. 1.0) color format",
				"regex": "hsva[(][ ]*(?P<H>dec)[ ]*[,][ ]*(?P<S>perc)[ ]*[,][ ]*(?P<V>perc)[ ]*[,][ ]*(?P<A>float)[ ]*[)]",
				"white": "hsva(0, 0%, 100%, 1.)"
			},
			"rgb":
			{
				"description": "rgb(255,255,100%) color format",
				"regex": "rgb[(][ ]*(?P<R>dec|perc)[ ]*[,][ ]*(?P<G>dec|perc)[ ]*[,][ ]*(?P<B>dec|perc)[ ]*[)]",
				"white": "rgb(255, 255, 100%)"
			},
			"rgba":
			{
				"description": "rgba(255,255,100%,1) color format",
				"regex": "rgba[(][ ]*(?P<R>dec|perc)[ ]*[,][ ]*(?P<G>dec|perc)[ ]*[,][ ]*(?P<B>dec|perc)[ ]*[,][ ]*(?P<A>float)[ ]*[)]",
				"white": "rgba(255, 255, 100%, 1)"
			},
			"sharp3":
			{
				"after": "sharp4",
				"description": "Hex #RGB color format",
				"regex": "#(?P<R>hex)(?P<G>hex)(?P<B>hex)",
				"white": "#FFF"
			},
			"sharp4":
			{
				"after": "sharp6",
				"description": "Hex #RGBA color format",
				"regex": "#(?P<R>hex)(?P<G>hex)(?P<B>hex)(?P<A>hex)",
				"white": "#FFFF"
			},
			"sharp6":
			{
				"after": "sharp8",
				"description": "Hex #RRGGBBAA color format",
				"regex": "#[0-9a-fA-F]{6}",
				"white": "#FFFFFF"
			},
			"sharp8":
			{
				"description": "Hex #RRGGBBAA color format",
				"regex": "#[0-9a-fA-F]{8}",
				"white": "#FFFFFFFF"
			}
		}
	},
	"search_colors_in":
	{
		"all_content":
		{
			"color_highlighters":
			{
				"color_scheme":
				{
					"enabled": true,
					"highlight_style": "text"
				},
				"gutter_icons":
				{
					"enabled": false,
					"icon_style": "circle"
				},
				"phantoms":
				{
					"enabled": false,
					"length": 2,
					"style": "right"
				}
			},
			"enabled": true
		},
		"hover":
		{
			"color_highlighters":
			{
				"color_scheme":
				{
					"enabled": false,
					"highlight_style": "filled"
				},
				"gutter_icons":
				{
					"enabled": false,
					"icon_style": "circle"
				},
				"phantoms":
				{
					"enabled": false,
					"length": 2,
					"style": "right"
				}
			},
			"enabled": true
		},
		"selection":
		{
			"color_highlighters":
			{
				"color_scheme":
				{
					"enabled": false,
					"highlight_style": "filled"
				},
				"gutter_icons":
				{
					"enabled": false,
					"icon_style": "circle"
				},
				"phantoms":
				{
					"enabled": true,
					"length": 2,
					"style": "right"
				}
			},
			"enabled": true
		}
	}
}
```
**Color Scheme:** `Packages/Monokai Neue/Monokai-Neue.tmTheme`
**ST Log:**
```
startup, version: 3147 osx x64 channel: dev
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/leblancc/Library/Application Support/Sublime Text 3/Packages
state path: /Users/leblancc/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/leblancc/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
Errors parsing theme:
icon_folder_loading is missing layer0.opacity, setting to 1.0 for backwards compatibility
icon_file_type is missing layer0.opacity, setting to 1.0 for backwards compatibility
pre session restore time: 0.719238
using gpu buffer for window
startup time: 0.836188
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin A File Icon.A File Icon
reloading plugin ApplySyntax.ApplySyntax
reloading plugin ApplySyntax.support
reloading plugin Boxy Theme.BT
reloading plugin Boxy Theme.Icons
reloading plugin Color Highlighter.color_converter
reloading plugin Color Highlighter.color_highlighter
reloading plugin Color Highlighter.color_hover_listener
reloading plugin Color Highlighter.color_scheme
reloading plugin Color Highlighter.color_scheme_color_highlighter
reloading plugin Color Highlighter.color_searcher
reloading plugin Color Highlighter.color_selection_listener
reloading plugin Color Highlighter.colors
reloading plugin Color Highlighter.content_listener
reloading plugin Color Highlighter.convert_color_command
reloading plugin Color Highlighter.css_colors
reloading plugin Color Highlighter.dummy_event_listener
reloading plugin Color Highlighter.gutter_icons_color_highlighter
reloading plugin Color Highlighter.load_resource
reloading plugin Color Highlighter.main
reloading plugin Color Highlighter.path
reloading plugin Color Highlighter.phantoms_color_highlighter
reloading plugin Color Highlighter.pick_color_command
reloading plugin Color Highlighter.regex_compiler
reloading plugin Color Highlighter.regions
reloading plugin Color Highlighter.set_setting_command
reloading plugin Color Highlighter.settings
reloading plugin Color Highlighter.st_helper
reloading plugin Color Highlighter.topsort
reloading plugin GitGutter.plugin
reloading plugin Markdown Preview.helper
reloading plugin Markdown Preview.markdown_settings
reloading plugin Markdown Preview.markdown_wrapper
reloading plugin Markdown Preview.MarkdownPreview
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin Skins.skins
reloading plugin SublimeLinter-contrib-htmllint.linter
SublimeLinter: htmllint linter loaded 
reloading plugin SublimeLinter-contrib-sass-lint.linter
SublimeLinter: sass linter loaded 
reloading plugin SublimeLinter-contrib-tslint.linter
SublimeLinter: tslint linter loaded 
reloading plugin SublimeLinter-csslint.linter
SublimeLinter: csslint linter loaded 
reloading plugin SublimeLinter-jsxhint.linter
SublimeLinter: jsxhint linter loaded 
reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
reloading plugin SublimeCodeIntel.ordereddict
reloading plugin SublimeCodeIntel.SublimeCodeIntel
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
reloading plugin SublimeLinter-contrib-eslint.linter
SublimeLinter: eslint linter loaded 
reloading plugin SublimeLinter-contrib-stylelint.linter
SublimeLinter: stylelint linter loaded 
reloading plugin TypeScript.main
2017-10-09 10:57:48,672: 140736567153600: WARNING: TypeScript plugin initialized.
plugins loaded
lang_service_enabled: True
Path of tsserver.js: /Users/leblancc/Library/Application Support/Sublime Text 3/Packages/TypeScript/tsserver/tsserver.js
Path of tsc.js: /Users/leblancc/Library/Application Support/Sublime Text 3/Packages/TypeScript/tsserver/tsc.js
Unable to find executable file for node on path list: /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:$NVM_BIN
To specify the node executable file name, use the 'node_path' setting
2017-10-09 10:57:48,675: 140736567153600: ERROR: can not send request; node process not running
ref view not found
SublimeLinter: debug mode: off 
SublimeLinter: csslint activated: /Users/leblancc/.nvm/versions/node/v6.11.3/bin/csslint 
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 210, in on_api_ready
    m.plugin_loaded()
  File "main in /Users/leblancc/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 606, in plugin_loaded
  File "main in /Users/leblancc/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 319, in init
  File "main in /Users/leblancc/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 197, in provide_fake_color_scheme
  File "main in /Users/leblancc/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 188, in provide_fake_color_scheme_data
  File "color_scheme in /Users/leblancc/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 43, in parse_color_scheme
  File "./python3.3/xml/etree/ElementTree.py", line 1356, in XML
  File "<string>", line None
xml.etree.ElementTree.ParseError: XML or text declaration not at start of entity: line 6, column 0
environment variables loaded using: /bin/bash -l
Package Control: Skipping automatic upgrade, last run at 2017-10-09 10:09:13, next run at 2017-10-09 11:09:13 or after
```

**Comment by Monnoroch** [comment]
Thanks for a good bug report! Your color scheme appears to be malformed or incompatible with the xml library in some other way. Can you please send it to me so I can look into it?

**Comment by LeBlaaanc** [comment]
@Monnoroch per your suggestion I tried a different theme "Monkai Extended" and the xml error went away however I still don't see any color highlighting? I've attached both schemes. I use Boxy Monokai theme if that sheds any light on the subject. Thanks for your help.

[Monokai Neue.sublime-package.zip](https://github.com/Monnoroch/ColorHighlighter/files/1369441/Monokai.Neue.sublime-package.zip)
[Monokai Extended.sublime-package.zip](https://github.com/Monnoroch/ColorHighlighter/files/1369440/Monokai.Extended.sublime-package.zip)

**Comment by LeBlaaanc** [comment]
@Monnoroch any other ideas here why this pacakge doesn't seem to work or how I could debug?

**Comment by LeBlaaanc** [comment]
Just to report back, I think the TypeScript package was suppressing my debug output for this package so I wasn't able to see the convert command error. Using something like `Monokai JSON+` and combination of fixing the convert command path or disabling the gutter icons seemed to clear this up.
