### ISSUE TITLE
Settings reference errors

### ISSUE THREAD

**Issue by Manifold0** [Monnoroch/ColorHighlighter#400]
When opening a new document:
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 737, in is_checked_
    ret = self.is_checked(**args)
  File "set_setting_command in /Users/ncox1/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 146, in is_checked
  File "set_setting_command in /Users/ncox1/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 207, in _get_setting
KeyError: 'style'
```

And when attempting to change the style from the settings dropdown menu:
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 780, in run_
    return self.run(**args)
  File "set_setting_command in /Users/ncox1/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 122, in run
  File "set_setting_command in /Users/ncox1/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 212, in _set_setting
  File "settings in /Users/ncox1/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 33, in __init__
  File "settings in /Users/ncox1/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 212, in __init__
  File "settings in /Users/ncox1/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 225, in __init__
KeyError: 'description'
```

**Comment by Manifold0** [comment]
Actually, blowing away my User settings and rebuilding them seems to have resolved this. Not sure what the original issue was, maybe a missing key?

**Comment by Monnoroch** [comment]
The problem was that you've set some setting that is not supported.
