### ISSUE TITLE
ColorHighlighter doesn't work on windows 10 Sublime Text3

### ISSUE THREAD

**Issue by Wannaof** [Monnoroch/ColorHighlighter#409]
I tried removed this plugin and reinstalled many times. It doesn't work.
But several days ago, it works fine. 
![tim 20171026182621](https://user-images.githubusercontent.com/7333109/32048246-78fa7b7e-ba7b-11e7-94c7-c1094c3dd6d8.png)
When I install plugin via package control. This file checked in the image is created. However, under Sublime Text 3\Packages directory is nothing.
One thing confused me is when I right click in html page and chose 「insert color with color picker」
![tim 20171026183108](https://user-images.githubusercontent.com/7333109/32048366-db68d06c-ba7b-11e7-9bb8-60fe1b3caf83.png) The color picker shows, and Sublime Text 3\Packages\User directory created folder color highlighter. But hot key ctrl + shift + c doesn't work. Don't know why this happens.
Thanks for helping!

**Comment by APSlee** [comment]
Actually, It depends on the Plugin itself. 
Some Plugins just be installed to"Sublime Text 3/Installed Packages" folder, such as "DocBlockr" and "AutoFileName" and "SideBarEnhancements"plugins; 
some are just installed to "Sublime Text 3/Packages" folder, such as "LiveReload" and "ConvertToUTF8" and "SublimeCodeIntel" plugins; 
And Some are installed to both folders, such as "FileHeader" plugin. 
As to "Color Highlighter", it is installed to "Installed Packages" folder and "Package/User/Color Highlighter" folder(where the ColorPicker is installed).
Ur "Color Highligter" plugin doesn't work mostly becasue of the problem of themes in "Package/User/Color Highlighter/themes" folder.
So My suggestion is deleting all files that related to "Color Highlighter" thoroughly(remove it from package control and then delete the "Color Highlighter" folder in "Package/User") and then reinstalling it  from package control. 
My system is Win10Pro, Version 1703, OS Build 15063.296, and Sublime Text 3 Build 3143. If ur "Color Highlighter" still doesn't work maybe U wanna update ur ST3 or reinstall it.

BWT, what is your font_face？

**Comment by Wannaof** [comment]
@APSlee 
Thanks for your reply! Learned a lot.
I tried to remove Color Highlighter from package control and delete related folders. Then I reinstalled it from package control, it still doesn't work. The console printed "ImportError: No module named 'Color Highlighter.topsort'" error. I searched it but found nothing useful.
And my font_face is 'Consolas'.

**Comment by Monnoroch** [comment]
> ImportError: No module named 'Color Highlighter.topsort

This means the plugin was not installed properly. My guess is that you need to properly remove the incorrect manual installation and install it from PC.

**Comment by Monnoroch** [comment]
The installation on the original screenshot looks totally fine.

**Comment by slloyd88** [comment]
I installed this via the package installer but it fails to load:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 298, in on_api_ready
    plc()
  File "C:\Users\slloyd\AppData\Roaming\Sublime Text 3\Installed Packages\Color Highlighter.sublime-package\main.py", line 606, in plugin_loaded
    ColorHighlighterPlugin.init()
  File "C:\Users\slloyd\AppData\Roaming\Sublime Text 3\Installed Packages\Color Highlighter.sublime-package\main.py", line 319, in init
    ColorHighlighterPlugin._fake_color_scheme = ColorHighlighterPlugin.components.provide_fake_color_scheme()
  File "C:\Users\slloyd\AppData\Roaming\Sublime Text 3\Installed Packages\Color Highlighter.sublime-package\main.py", line 197, in provide_fake_color_scheme
    return self.provide_fake_color_scheme_data()[0]
  File "C:\Users\slloyd\AppData\Roaming\Sublime Text 3\Installed Packages\Color Highlighter.sublime-package\main.py", line 188, in provide_fake_color_scheme_data
    self._fake_color_scheme_data = parse_color_scheme(self.provide_color_scheme(), self._settings.debug)
  File "C:\Users\slloyd\AppData\Roaming\Sublime Text 3\Installed Packages\Color Highlighter.sublime-package\color_scheme.py", line 40, in parse_color_scheme
    color_scheme_content = load_resource.load_resource(color_scheme)
  File "C:\Users\slloyd\AppData\Roaming\Sublime Text 3\Installed Packages\Color Highlighter.sublime-package\load_resource.py", line 30, in load_resource
    return sublime.load_resource(file_path)
  File "C:\Program Files\Sublime Text 3\sublime.py", line 192, in load_resource
    raise IOError("resource not found")
OSError: resource not found
Package Control: No updated packages

**Comment by srkanoi** [comment]
Workaround:
Uninstall "Color Highlighter" and install "Color Highlight". It's perfect!
