### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by evandrocoan** [Monnoroch/ColorHighlighter#417]
```
reloading settings Packages/Default/Preferences.sublime-settings
Traceback (most recent call last):
  File "D:\SublimeText\Data\Packages\Color Highlighter\main.py", line 341, in _on_preferences_change
    ColorHighlighterPlugin.restart()
  File "D:\SublimeText\Data\Packages\Color Highlighter\main.py", line 347, in restart
    ColorHighlighterPlugin.init()
  File "D:\SublimeText\Data\Packages\Color Highlighter\main.py", line 319, in init
    ColorHighlighterPlugin._fake_color_scheme = ColorHighlighterPlugin.components.provide_fake_color_scheme()
  File "D:\SublimeText\Data\Packages\Color Highlighter\main.py", line 197, in provide_fake_color_scheme
    return self.provide_fake_color_scheme_data()[0]
  File "D:\SublimeText\Data\Packages\Color Highlighter\main.py", line 188, in provide_fake_color_scheme_data
    self._fake_color_scheme_data = parse_color_scheme(self.provide_color_scheme(), self._settings.debug)
  File "D:\SublimeText\Data\Packages\Color Highlighter\color_scheme.py", line 35, in parse_color_scheme
    fake_color_scheme = path.fake_color_scheme_path(color_scheme, path.ABSOLUTE)
  File "D:\SublimeText\Data\Packages\Color Highlighter\path.py", line 145, in fake_color_scheme_path
    file_name = os.path.basename(color_scheme)
  File "./python3.3/ntpath.py", line 249, in basename
  File "./python3.3/ntpath.py", line 220, in split
  File "./python3.3/ntpath.py", line 162, in splitdrive
TypeError: object of type 'NoneType' has no len()
```

Lines:
```python
File: Data/Packages/Color Highlighter/path.py
136: def fake_color_scheme_path(color_scheme, relative):
137:     """
138:     Given a color scheme, get a fake color scheme path.
139: 
140:     Arguments:
141:     - color_scheme - color scheme sublime relative path.
142:     - relative - whether to get an absolute path or a relative to sublime packages directory.
143:     Returns a path to the fake color scheme for this color scheme.
144:     """
145:     file_name = os.path.basename(color_scheme)
146:     path = os.path.join(themes_path(relative), file_name)
147:     if relative:
148:         path = normalize_path_for_st(path)
149:     return path
150: 
```
My settings file is under git, then this happened when there was a conflict on the color_scheme setting.

**Comment by Monnoroch** [comment]
I don't understand. Please provide an example of a settings file that reproduces the problem.

**Comment by evandrocoan** [comment]
When a file do conflict under git, it is put like this:
```javascript
{
    "search_colors_in": {
        "selection": {
<<<<<<< HEAD
            "enabled": false,
=======
            "enabled": true,
>>>>>>> branch-a
            "color_highlighters": {
            ...
```
Have you ever seems those?

When this happens Sublime Text cannot parse the setting file anymore. Then it do errors. 

I got the stack trace above when I had and fixed a conflict on some setting file. I am not sure why would this package do a stack on these cases.

**Comment by Monnoroch** [comment]
Well, surely you can see that this settings file is invalid. Hence the plugin's failing. There's absolutely nothing I can do here, ST can't parse invalid json files.
