### ISSUE TITLE
Can't make the plugin load because of some issue

### ISSUE THREAD

**Issue by ka8725** [Monnoroch/ColorHighlighter#418]
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 658, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "main in /Users/ka8725/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 658, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "phantoms_color_highlighter in /Users/ka8725/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 17, in <module>
  File "phantoms_color_highlighter in /Users/ka8725/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 40, in PhantomColorHighlighter
AttributeError: 'module' object has no attribute 'LAYOUT_INLINE'
```

**Comment by Monnoroch** [comment]
Your ST installation is broken somehow.

**Comment by RainThinks** [comment]
same here

**Comment by RainThinks** [comment]
same here. fixed by update ST to latest.
