### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by JamiesonWarner** [Monnoroch/ColorHighlighter#423]
Installing ColorHighlighter from Package Control gives the console message:

```
reloading plugin Color Highlighter.main
Traceback (most recent call last):
  File "/opt/sublime_text_3/sublime_plugin.py", line 106, in reload_plugin
    unload_module(m)
  File "/opt/sublime_text_3/sublime_plugin.py", line 61, in unload_module
    module.plugin_unloaded()
  File "main in /home/jamie/.config/sublime-text-3/Installed Packages/Color Highlighter.sublime-package", line 611, in plugin_unloaded
  File "settings in /home/jamie/.config/sublime-text-3/Installed Packages/Color Highlighter.sublime-package", line 30, in __init__
AttributeError: 'NoneType' object has no attribute 'deepcopy'
```

And upon reopening ST:

```
Traceback (most recent call last):
  File "/opt/sublime_text_3/sublime_plugin.py", line 210, in on_api_ready
    m.plugin_loaded()
  File "main in /home/jamie/.config/sublime-text-3/Installed Packages/Color Highlighter.sublime-package", line 603, in plugin_loaded
  File "settings in /home/jamie/.config/sublime-text-3/Installed Packages/Color Highlighter.sublime-package", line 32, in __init__
  File "settings in /home/jamie/.config/sublime-text-3/Installed Packages/Color Highlighter.sublime-package", line 96, in __init__
  File "settings in /home/jamie/.config/sublime-text-3/Installed Packages/Color Highlighter.sublime-package", line 116, in __init__
  File "settings in /home/jamie/.config/sublime-text-3/Installed Packages/Color Highlighter.sublime-package", line 132, in __init__
  File "settings in /home/jamie/.config/sublime-text-3/Installed Packages/Color Highlighter.sublime-package", line 191, in __init__
AssertionError
```

Sublime Text 3.0, Build 3143.
Ubuntu xenial.

**Comment by Monnoroch** [comment]
I can't reproduce the problem.I also have an Ubuntu and both installation and restarting on the same ST build goes as smooth as it possibly can. Could you maybe retry intalling it from scratch (after removing everything related to CH in */User? And if it fails too, please include a complete log.

**Comment by JamiesonWarner** [comment]
Hi, here is the full output after using Package Control to remove Color Highlighter, then deleting the /User/Color Highlighter directory and reinstalling with Package Control:

```ignored packages updated to: ["Color Highlighter", "MagicPython", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["MagicPython", "Vintage"]
reloading plugin Color Highlighter.color_converter
reloading plugin Color Highlighter.color_highlighter
reloading plugin Color Highlighter.color_hover_listener
reloading plugin Color Highlighter.color_scheme
reloading plugin Color Highlighter.color_scheme_color_highlighter
reloading plugin Color Highlighter.color_searcher
reloading plugin Color Highlighter.color_selection_listener
reloading plugin Color Highlighter.colors
reloading plugin Color Highlighter.content_listener
reloading plugin Color Highlighter.convert_color_command
reloading plugin Color Highlighter.css_colors
reloading plugin Color Highlighter.dummy_event_listener
reloading plugin Color Highlighter.gutter_icons_color_highlighter
reloading plugin Color Highlighter.load_resource
reloading plugin Color Highlighter.main
Traceback (most recent call last):
  File "/opt/sublime_text_3/sublime_plugin.py", line 157, in reload_plugin
    m.plugin_loaded()
  File "main in /home/jamie/.config/sublime-text-3/Installed Packages/Color Highlighter.sublime-package", line 606, in plugin_loaded
  File "main in /home/jamie/.config/sublime-text-3/Installed Packages/Color Highlighter.sublime-package", line 319, in init
  File "main in /home/jamie/.config/sublime-text-3/Installed Packages/Color Highlighter.sublime-package", line 197, in provide_fake_color_scheme
  File "main in /home/jamie/.config/sublime-text-3/Installed Packages/Color Highlighter.sublime-package", line 188, in provide_fake_color_scheme_data
  File "color_scheme in /home/jamie/.config/sublime-text-3/Installed Packages/Color Highlighter.sublime-package", line 40, in parse_color_scheme
  File "load_resource in /home/jamie/.config/sublime-text-3/Installed Packages/Color Highlighter.sublime-package", line 30, in load_resource
  File "/opt/sublime_text_3/sublime.py", line 192, in load_resource
    raise IOError("resource not found")
OSError: resource not found
reloading plugin Color Highlighter.path
reloading plugin Color Highlighter.phantoms_color_highlighter
reloading plugin Color Highlighter.pick_color_command
reloading plugin Color Highlighter.regex_compiler
reloading plugin Color Highlighter.regions
reloading plugin Color Highlighter.set_setting_command
reloading plugin Color Highlighter.settings
reloading plugin Color Highlighter.st_helper
reloading plugin Color Highlighter.topsort
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings```

If I instead install by cloning the git repository into the Packages directory, I get the same traceback.

**Comment by Monnoroch** [comment]
Right now it says that your color scheme doesn't exist. Can you please check that the color scheme set in your ST preferences actually does exist?

**Comment by Monnoroch** [comment]
To be more precise:
1. Click `Preferences > Settings`, find the `"color_scheme"` setting and check that the file exists in your packages directory. Your log file says that it doesn't.

**Comment by JamiesonWarner** [comment]
Hi, thank you, it seems it was a configuration problem on my end -- my color scheme was lost upon upgrading to ST3, though it still displayed correctly. Upon switching to one of the ST3 schemes, the plugin works correctly.
