### ISSUE TITLE
Can't insert color with color picker

### ISSUE THREAD

**Issue by predragnikolic** [Monnoroch/ColorHighlighter#432]
When I right click a color an chose insert color with color picker, nothing happens.

I get an error message in the console

`Traceback (most recent call last):
  File "pick_color_command in /home/predrag/.config/sublime-text-3/Installed Packages/Color Highlighter.sublime-package", line 63, in _open_color_picker
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
PermissionError: [Errno 13] Permission denied`

**Comment by etienned** [comment]
Same thing over here.
