### ISSUE TITLE
AssertionError in mac os 10.13.1 and  package is no longer working

### ISSUE THREAD

**Issue by zymr-keshav** [Monnoroch/ColorHighlighter#434]
system: macOS 10.13.1
sublime text 3 build 3143

I have installed ColorHighlighter and it was working fine so far but recently I have tried to change the settings such as changing the block color display settings  such as

*Tools > Color Highlighter > Color Highlighters > Highlight colors in all text > Highlight colors with blocks* _To the right of color_ to _None_ 

I tried many other setting options and this is immediately reflecting and working fine BUT when I restart the sublime, everything stopped working even changes in the setting are not remains, always fallback to the previously selected settings.

so I uninstall and install again this packages ( to get the default setting)

but nothing is working, it seems dead and there is some error stack in the console continuously

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 780, in run_
    return self.run(**args)
  File "set_setting_command in /Users/keshav.m/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 122, in run
  File "set_setting_command in /Users/keshav.m/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 212, in _set_setting
  File "settings in /Users/keshav.m/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 32, in __init__
  File "settings in /Users/keshav.m/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 96, in __init__
  File "settings in /Users/keshav.m/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 116, in __init__
  File "settings in /Users/keshav.m/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 132, in __init__
  File "settings in /Users/keshav.m/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 191, in __init__
AssertionError

```

Please suggest me what to do?

**Comment by eballeste** [comment]
@zymr-keshav did you ever figure this out? i'm going through the same issue, decided to update my settings for the first time today, noticed that it was acting a little buggy when changing the settings, then it stopped working all together, tried to uninstall / reinstall and started getting the assertion error everytime i try to change any of the settings.

**Comment by eballeste** [comment]
uninstalled the package and noticed that there were still colorhighlighter files in the user settings folder, deleted both the folder and the individual user setting...

reopened sublime, installed the package and got a warning about some type of missing colorhighlighter / material theme settings file.... ignored it, reinstalled color highlighter, profit.

**Comment by zymr-keshav** [comment]
yes. the same behavior I am facing. even I uninstalled but it still gives error and snaps of color highlighter in the sublime text editor.

**Comment by eballeste** [comment]
it's working for me after doing the steps from my last comment

**Comment by Spaxe** [comment]
same problem here, mac os 10.12.6, sublime text 3158

**Comment by mymacy** [comment]
same problem here on windows machine. 

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 106, in reload_plugin
    unload_module(m)
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 61, in unload_module
    module.plugin_unloaded()
  File "main in C:\Users\marce\AppData\Roaming\Sublime Text 3\Installed Packages\Color Highlighter.sublime-package", line 611, in plugin_unloaded
  File "settings in C:\Users\marce\AppData\Roaming\Sublime Text 3\Installed Packages\Color Highlighter.sublime-package", line 30, in __init__
AttributeError: 'NoneType' object has no attribute 'deepcopy'
