### ISSUE TITLE
Problem on load of package

### ISSUE THREAD

**Issue by raphaelfabeni** [Monnoroch/ColorHighlighter#436]
Hey guys! Anyone already saw something like that?

![screen shot 2018-01-12 at 10 53 17 am](https://user-images.githubusercontent.com/1345662/34876006-d9971af8-f786-11e7-9722-a07c6866b4b1.png)

* Sublime Version 3.0, Build 3143
* macOS Sierra version 10.12.6

**Comment by raphaelfabeni** [comment]
```sh
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 210, in on_api_ready
    m.plugin_loaded()
  File "main in /Users/rfabeni/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 603, in plugin_loaded
  File "settings in /Users/rfabeni/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 32, in __init__
  File "settings in /Users/rfabeni/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 97, in __init__
  File "settings in /Users/rfabeni/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 116, in __init__
  File "settings in /Users/rfabeni/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 132, in __init__
  File "settings in /Users/rfabeni/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 191, in __init__
AssertionError
```

**Comment by GoMrPickles** [comment]
I am having a nearly identical error on Ubuntu 16.04. I originally posted about it here:
https://github.com/Monnoroch/ColorHighlighter/issues/298#issuecomment-376041814
This thread (maybe others?) is more appropriate, I think. Console log attached.
[sublime-text.log](https://github.com/Monnoroch/ColorHighlighter/files/1852167/sublime-text.log)

**Comment by GoMrPickles** [comment]
I fixed this by:
-removing Color Highlighter using Package Control within Sublime Text
-deleting everything related to Color Highlighter in `~/.config/sublime-text-3/Packages/User`, such as the settings files
-deleting everything in the package control installer cache (`~/.config/sublime-text-3/Packages/User/Package Control.cache`)
-reinstall Color Highlighter from Package Control in ST

I can no longer _find_ the Settings files, but... Color Highlighter works, and the Color Picker can be launched. Progress!

**Comment by raphaelfabeni** [comment]
It worked @GoMrPickles !
Thanks!
🤘
