### ISSUE TITLE
[ret = self.is_checked(**args)] Works when it feels like it lol

### ISSUE THREAD

**Issue by roblav96** [Monnoroch/ColorHighlighter#443]
This error occasionally spams my console when I open a highlightable file:
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 879, in is_checked_
    ret = self.is_checked(**args)
  File "set_setting_command in /Users/----/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 144, in is_checked
  File "set_setting_command in /Users/----/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 206, in _get_setting
KeyError: 'color_highlighters'
...
```

It's strange because sometimes it'll work, other time's it just wont. I find that quickly toggling my color scheme can resolve it sometimes.

`startup, version: 3157 osx x64 channel: dev`

**Comment by dortamiguel** [comment]
Im getting the same
