### ISSUE TITLE
new color scheme format, .sublime-color-scheme

### ISSUE THREAD

**Issue by BoLaMN** [Monnoroch/ColorHighlighter#444]
Hey just a heads up, 

Sublime Text 3149+ introduces a new JSON based *.sublime-color-scheme format. All default color schemes were converted to this new format which causes ColorHighlighter to crash on load.

```Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 210, in on_api_ready
    m.plugin_loaded()
  File "main in /Users/nathan/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 606, in plugin_loaded
  File "main in /Users/nathan/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 319, in init
  File "main in /Users/nathan/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 197, in provide_fake_color_scheme
  File "main in /Users/nathan/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 188, in provide_fake_color_scheme_data
  File "color_scheme in /Users/nathan/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 43, in parse_color_scheme
  File "./python3.3/xml/etree/ElementTree.py", line 1356, in XML
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0```

Cheers

**Comment by frank270** [comment]
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 283, in on_api_ready
    m.plugin_loaded()
  File "/Users/n/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package/main.py", line 606, in plugin_loaded
    ColorHighlighterPlugin.init()
  File "/Users/n/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package/main.py", line 319, in init
    ColorHighlighterPlugin._fake_color_scheme = ColorHighlighterPlugin.components.provide_fake_color_scheme()
  File "/Users/n/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package/main.py", line 197, in provide_fake_color_scheme
    return self.provide_fake_color_scheme_data()[0]
  File "/Users/n/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package/main.py", line 188, in provide_fake_color_scheme_data
    self._fake_color_scheme_data = parse_color_scheme(self.provide_color_scheme(), self._settings.debug)
  File "/Users/n/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package/color_scheme.py", line 43, in parse_color_scheme
    color_scheme_xml = ElementTree.fromstring(color_scheme_content)
  File "./python3.3/xml/etree/ElementTree.py", line 1356, in XML
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0


Same~

environment: macos sierra
python version:2.7.15
imagemagick installed.

**Comment by XjSv** [comment]
Same problem here as well.
```Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 283, in on_api_ready
    m.plugin_loaded()
  File "C:\Users\atres\AppData\Roaming\Sublime Text 3\Installed Packages\Color Highlighter.sublime-package\main.py", line 606, in plugin_loaded
    ColorHighlighterPlugin.init()
  File "C:\Users\atres\AppData\Roaming\Sublime Text 3\Installed Packages\Color Highlighter.sublime-package\main.py", line 319, in init
    ColorHighlighterPlugin._fake_color_scheme = ColorHighlighterPlugin.components.provide_fake_color_scheme()
  File "C:\Users\atres\AppData\Roaming\Sublime Text 3\Installed Packages\Color Highlighter.sublime-package\main.py", line 197, in provide_fake_color_scheme
    return self.provide_fake_color_scheme_data()[0]
  File "C:\Users\atres\AppData\Roaming\Sublime Text 3\Installed Packages\Color Highlighter.sublime-package\main.py", line 188, in provide_fake_color_scheme_data
    self._fake_color_scheme_data = parse_color_scheme(self.provide_color_scheme(), self._settings.debug)
  File "C:\Users\atres\AppData\Roaming\Sublime Text 3\Installed Packages\Color Highlighter.sublime-package\color_scheme.py", line 43, in parse_color_scheme
    color_scheme_xml = ElementTree.fromstring(color_scheme_content)
  File "./python3.3/xml/etree/ElementTree.py", line 1356, in XML
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0```

**Comment by alisomay** [comment]
Same here..
