### ISSUE TITLE
Not working with 3176 ?

### ISSUE THREAD

**Issue by axessweb** [Monnoroch/ColorHighlighter#456]
Hi,

On Windows... seems not working with ST3 (3176)

Any help ?

**Comment by axessweb** [comment]
Ok.. 

![image](https://user-images.githubusercontent.com/1068898/40166191-449cf8d8-59be-11e8-9949-d956a115d867.png)


Help me?

**Comment by indextwo** [comment]
Same. At first I thought I'd screwed up my syntax somewhere, but then checked other files & remembered that it was fine prior to the 3176 update. 

It was suggested in #452 that it might be to do with the `file_extensions` setting, but mine looks fine: 

`"file_extensions": [".css", ".less", ".scss", ".sass", ".styl"],`

That was from the Default profile. I added it to my User profile just to make sure and restarted ST, but no dice.

**Comment by crimerrsplay** [comment]
Same

**Comment by axessweb** [comment]
@indextwo tested.. but not working

**Comment by Senses96** [comment]
Same problem here

**Comment by maenette** [comment]
Same: Windows 10 Home : Sublime build 3176.

**Comment by 0speedy** [comment]
Same here, Windows 7 Pro x64, Sublime v 3176. I've spent good half an hour by changing settings, re-installing and other weird stuff. 

May help that after installation there's not even a subfolder "Color Highlighter" in ""c:\Users\<User>\AppData\Roaming\Sublime Text 3\Packages\" where default settings (and who knows what else) should be.

**Comment by 0speedy** [comment]
**Working now!**

Here's what I did:
1. Open default settings for Color Highlighter: Preferences -> Package Settings -> Color Highlighter -> Settings - Default
2. Copy content and save it anywhere for now, we'll need it later
3. Create subfolder "Color Highlighter" in "c:\Users\<User>\AppData\Roaming\Sublime Text 3\Packages" 
4. Copy there content of "c:\Users\<User>\AppData\Roaming\Sublime Text 3\Packages\User\Color Highlighter"
5. Copy file "c:\Users\<User>\AppData\Roaming\Sublime Text 3\Packages\User\ColorHighlighter.sublime-settings" to "c:\Users\<User>\AppData\Roaming\Sublime Text 3\Packages\Color Highlighter"
6. Edit this new copied settings file and paste there content from step 2 _(we just created missing default setting file)_
7. Open Preferences -> Package Settings -> Color Highlighter -> Settings - User and either delete all content or paste there the content from step 2 (it has the same result). 
8. Restart sublime just to be sure.

Looks like there were 2 issues: subfolder in Packages was not created on installation + user settings are somehow broken by default (settings.py was complaining about the value for "phantoms" on line 191).

Hope it will help you all!

**Comment by axessweb** [comment]
No working for me..  :(

![image](https://user-images.githubusercontent.com/1068898/40267543-7eee2542-5b5e-11e8-8248-586cd5f93e46.png)

**Comment by indextwo** [comment]
@0speedy Unfortunately that doesn't work for me either. I'm not seeing stack traces of any errors, but I tried following the steps twice and it's made no difference.

**Comment by 0speedy** [comment]
@indextwo Did you try re-installing the package before trying those steps? I also noticed that when I do certain changes to the settings using menu Tools -> Color Highlighter it stops working. So there's definitely some issue with user settings.

**Comment by indextwo** [comment]
@0speedy Uninstalled the package, reinstalled it, tried all the steps again, but nothing is happening. Confirmed all the steps, and my user settings file is currently empty. Tried it by copying across my Default settings and still nothing. Tried it with all the steps but didn't copy across my Defaults (just left them as is, as per the fresh install) and nothing.

**Comment by ltpquang** [comment]
Same problem: OS X with ST3 3176, @0speedy's solution doesn't work for me :(

**Comment by 0speedy** [comment]
I'm sorry to hear that guys. I guess it worked for me as I have new and almost clean ST3 installation without any packages. Try to make any change to user settings and watch Console to get any hints about what's going wrong. 
@axessweb Looks like your issue is somehow connected to the theme/color scheme you're using. Did you try using one of the default ones?

**Comment by axessweb** [comment]
@0speedy That's what I thought, but I use monokai by default. You.. what's your theme?

**Comment by 0speedy** [comment]
@axessweb I'm using Afterglow color scheme with Default theme, 

Btw you guys know that for some features (I think only the gutter icons) you need ImageMagick, right?

One more thing - do not change the settings from the menu Tools -> Color Highlighter, do it directly in user settings file.

**Comment by L-sixhang** [comment]
Same problem here +1

**Comment by JasperKloosterman** [comment]
> Traceback (most recent call last):
>   File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 283, in on_api_ready
>     m.plugin_loaded()
>   File "/Users/jkloosterman/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package/main.py", line 603, in plugin_loaded
>     debug = Settings(sublime.load_settings(COLOR_HIGHLIGHTER_SETTINGS_NAME)).debug
>   File "/Users/jkloosterman/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package/settings.py", line 32, in __init__
>     self.search_colors_in = _SearchColorsSettings(copy.deepcopy(settings.get("search_colors_in", {})))
>   File "/Users/jkloosterman/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package/settings.py", line 96, in __init__
>     self.all_content = _ColorSearcherSettings(settings.get("all_content", {}), "all_content")
>   File "/Users/jkloosterman/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package/settings.py", line 116, in __init__
>     self.color_highlighters = _ColorHighlighterSettings(settings.get("color_highlighters", {}))
>   File "/Users/jkloosterman/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package/settings.py", line 132, in __init__
>     self.phantoms = _PhantomsColorHighlighterSettings(settings.get("phantoms", {}))
>   File "/Users/jkloosterman/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package/settings.py", line 191, in __init__
>     assert self.style in self.VALID_STYLES
> AssertionError

Same here

**Comment by vact** [comment]
Same here

**Comment by benmarten** [comment]
+1, this plugin is broken with latest version

**Comment by Mystic-Ervo** [comment]
Same here: ST3.1.1 (3176); Windows 10 Pro & **Win2K8 R2** Enterprise

**Comment by codenigma1** [comment]
many plugin is not working with this latest version. like sidebar enhancement and build window (output).

**Comment by vinsonw** [comment]
windows10 professional & ST3 3176 not working.

**Comment by maegul** [comment]
@0speedy Your advice worked for me.  

It appeared to be a problem with the package's behaviour of deleting settings files (due to major rewrite).  Once settings files were in the rights places, the package kicked in and rewrote them, but in the appropriate format (apparently).

Interesting to note that the maintainer admits to not testing on Windows and Mac, so I bet the problem is OS specific (Unfortunate really - Windows and Mac are both the more popular OS for this package than Linus).

Some have suggested Color Highlight as an alternative to this package.  For the latest build (3176), I also had a problem with it, and, it is much simpler in its functionality.  So simple that I persevered to get this package working again.  Would recommend - options for how to show colors are hard to go without.

**Comment by tim-ardan** [comment]
I have the same problem and I'm on Linux (Ubuntu 18.04) running ST3 (Build 3176).

**Comment by ejexxeffer** [comment]
So sad, i have the same problem. Without this plugin work in ST3 not so amazing.

**Comment by nhmarahoesin** [comment]
Same here, windows7 + ST3 3176 not working too

**Comment by Edgar-Cortez** [comment]
@maegul Thanks for the recommendation of another package you mentioned "Color Highlight". I installed this and "Color Picker" and I am now good to go. 

I do really want to figure out how to get "Color Highlighter" working though just for learning purposes.

**Comment by cgtspl** [comment]
Same here, windows10 + ST3 3176 not working too...

Where to next?

**Comment by indextwo** [comment]
Thanks to [the tip](https://github.com/Monnoroch/ColorHighlighter/issues/456#issuecomment-455002498) from @EdgarCortez1 I switched to [Color Highlight](https://packagecontrol.io/packages/Color%20Highlight) and it highlights all my hex colours in context and in the gutter in ST3. 

It's pretty much the exact same thing, and since it doesn't look like ColorHighlighter is going to be updated anytime soon (this ticket has been open since last May), Color Highlight looks like a good bet.

**Comment by convexbytes** [comment]
Same problem here, windows 10, ST 3176

**Comment by dusted** [comment]
This problem still exists, +1 OS X Yosemite 10.10.5

**Comment by murazi** [comment]
win10+ST 3176 **+1**

**Comment by AmrSubZero** [comment]
Same here, **Windows10 1903** & **ST v3.2.2 build 3211**

```
Error:
Invalid Parameter - TrueColorMatte

Highlighting colors with gutter icons is not supported with current ImageMagick setup. Try configuring the "icon_factory setting"
Traceback (most recent call last):

  	File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 298, in on_api_ready
    plc()
  
	File "C:\Users\PC\AppData\Roaming\Sublime Text 3\Installed Packages\Color Highlighter.sublime-package\main.py", line 606, in plugin_loaded
    ColorHighlighterPlugin.init()
  
	File "C:\Users\PC\AppData\Roaming\Sublime Text 3\Installed Packages\Color Highlighter.sublime-package\main.py", line 319, in init
    ColorHighlighterPlugin._fake_color_scheme = ColorHighlighterPlugin.components.provide_fake_color_scheme()
  
	File "C:\Users\PC\AppData\Roaming\Sublime Text 3\Installed Packages\Color Highlighter.sublime-package\main.py", line 197, in provide_fake_color_scheme
    return self.provide_fake_color_scheme_data()[0]
  
	File "C:\Users\PC\AppData\Roaming\Sublime Text 3\Installed Packages\Color Highlighter.sublime-package\main.py", line 188, in provide_fake_color_scheme_data
    self._fake_color_scheme_data = parse_color_scheme(self.provide_color_scheme(), self._settings.debug)
  
	File "C:\Users\PC\AppData\Roaming\Sublime Text 3\Installed Packages\Color Highlighter.sublime-package\color_scheme.py", line 40, in parse_color_scheme
    color_scheme_content = load_resource.load_resource(color_scheme)
  
	File "C:\Users\PC\AppData\Roaming\Sublime Text 3\Installed Packages\Color Highlighter.sublime-package\load_resource.py", line 30, in load_resource
    return sublime.load_resource(file_path)
  
	File "C:\Program Files\Sublime Text 3\sublime.py", line 192, in load_resource
    raise IOError("resource not found")

OSError: resource not found
```
